<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-16B2CL7O" failures="2" tests="2" name="Test(failed)" time="0.438" errors="0" timestamp="2024-07-13T15:30:56 IST">
  <testcase classname="TestNG.Retry_Test_cases" name="Test_Case_02" time="0.042">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNG.Retry_Test_cases.Test_Case_02(Retry_Test_cases.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test_Case_02 -->
  <testcase classname="TestNG.Retry_Test_cases" name="Test_Case_01" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNG.Retry_Test_cases.Test_Case_01(Retry_Test_cases.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test_Case_01 -->
  <testcase classname="TestNG.Retry_Test_cases" name="Test_Case_03" time="0.0">
    <ignored/>
  </testcase> <!-- Test_Case_03 -->
</testsuite> <!-- Test(failed) -->
